#!/bin/bash
# cronless-run-task — универсальный скрипт для запуска задач

TASK_NAME="$1"
if [ -z "$TASK_NAME" ]; then
    echo "Usage: $0 <task_name>"
    exit 1
fi

TASKS_DIR="$HOME/.config/systemd/user/cronless-tasks"

TASK_FILE="$TASKS_DIR/${TASK_NAME}"
if [ ! -f "$TASK_FILE" ]; then
    echo "Task $TASK_NAME not found!" >&2
    exit 1
fi

$TASK_FILE

EXIT_CODE=$?

exit $EXIT_CODE
